gui:
  # theme:
  #   activeBorderColor:
  #     - blue
  #     - bold
  #   inactiveBorderColor:
  #     - white
  #   optionsTextColor:
  #     - blue
  #   selectedLineBgColor:
  #     - default
  #   selectedRangeBgColor:
  #     - default
  #   cherryPickedCommitBgColor:
  #     - cyan
  #   cherryPickedCommitFgColor:
  #     - blue
  #   unstagedChangesColor:
  #     - red
  theme:
    activeBorderColor:
      - '#fab387'
      - bold
    inactiveBorderColor:
      - '#a6adc8'
    optionsTextColor:
      - '#89b4fa'
    selectedLineBgColor:
      - '#313244'
    # selectedRangeBgColor:
    #   - '#313244'
    cherryPickedCommitBgColor:
      - '#45475a'
    cherryPickedCommitFgColor:
      - '#fab387'
    unstagedChangesColor:
      - '#f38ba8'
    defaultFgColor:
      - '#cdd6f4'
    searchingActiveBorderColor:
      - '#f9e2af'

  showFileTree: true # for rendering changes files in a tree format
  showListFooter: true # for seeing the '5 of 20' message in list panels
  showRandomTip: true
  showBottomLine: true # for hiding the bottom information line (unless it has important information to tell you)
  showCommandLog: true
  showIcons: true

# disableStartupPopups: true
# notARepository: "skip" # one of: 'prompt' | 'create' | 'skip'
# os:
#   edit: "nvim"

git:
  paging:
    colorArg: always
    pager: diff-so-fancy

os:
  edit: "vim"
